# Site settings
title: Stephanie Cree
email: "cree.stephanie@utexas.edu"
description: > # this means to ignore newlines until "baseurl:"
  Stephanie Cree | Designer and Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://skcele.github.io" # the base hostname & protocol for your site
github_username:  skcele

# Build settings
markdown: kramdown
