# Site settings
title: Stephanie Cree
email: ""
description: > # this means to ignore newlines until "baseurl:"
  Here lies my work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://skcele.github.io" # the base hostname & protocol for your site
github_username:  skcele

# Build settings
markdown: kramdown
